// <auto-generated />
using HernandezJorge_API_Ej2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HernandezJorge_API_Ej2.Migrations
{
    [DbContext(typeof(HernandezJorge_API_Ej2Context))]
    [Migration("20231124004339_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HernandezJorge_API_Ej2.Models.Game", b =>
                {
                    b.Property<int>("JuegoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JuegoId"), 1L, 1);

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JuegoId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            JuegoId = 1,
                            GeneroId = 1,
                            Titulo = "Juego1"
                        },
                        new
                        {
                            JuegoId = 2,
                            GeneroId = 2,
                            Titulo = "Juego2"
                        },
                        new
                        {
                            JuegoId = 3,
                            GeneroId = 3,
                            Titulo = "Juego3"
                        });
                });

            modelBuilder.Entity("HernandezJorge_API_Ej2.Models.Genre", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneroId"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GeneroId");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GeneroId = 1,
                            Nombre = "Accion"
                        },
                        new
                        {
                            GeneroId = 2,
                            Nombre = "Aventura"
                        },
                        new
                        {
                            GeneroId = 3,
                            Nombre = "Carreras"
                        });
                });

            modelBuilder.Entity("HernandezJorge_API_Ej2.Models.Game", b =>
                {
                    b.HasOne("HernandezJorge_API_Ej2.Models.Genre", "Genero")
                        .WithMany("Juegos")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("HernandezJorge_API_Ej2.Models.Genre", b =>
                {
                    b.Navigation("Juegos");
                });
#pragma warning restore 612, 618
        }
    }
}
